project_id = "mkwnlztpyzjjhzfxgixx"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.get-shared-documents]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.vorsorge-chat]
verify_jwt = false

[functions.send-recovery-email]
verify_jwt = false