project_id = "mkwnlztpyzjjhzfxgixx"

[functions.create-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.get-shared-documents]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false